import Head from "next/head";
import Link from "next/link";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div
          style={{
            display: "flex",
            flexDirection: "column",
            fontSize: "32px",
            margin: "2rem",
          }}
        >
          <Link href="ssg">SSG</Link>
          <Link href="csr">CSR</Link>
          <Link href="ssr">SSR</Link>
        </div>
      </main>
    </>
  );
}
